name: Slack Notification
on:
  issues:
    types: opened
jobs:
  build:
    name: Build
    # runs-on: macOS-10.15
    runs-on: self-hosted
    steps:
      - uses: rtCamp/action-slack-notify@v2.0.2
        name: Slack Notifiaction
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: My Alert
          SLACK_TITLE: タイトル
          SLACK_MESSAGE: メッセージ送信テスト
