name: Slack Notification
on:
  issues:
    types: opened
jobs:
  build:
    name: Build
    runs-on: macOS-10.15
    steps:
      - name: Test1
        run: |
          echo "Hello, World!"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: My Alert
          SLACK_TITLE: タイトル
          SLACK_MESSAGE: メッセージです
