name: Slack Notification
# on:
#   issues:
#     types: [opened]
# env:
#   INCOMING_WEBHOOK_URL: "https://hooks.slack.com/services/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"
# with:
#   text: Hello, Slack!!
on: push
jobs:
  build:
    name: Build
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world
