name: Slack Notification
on:
  issues:
    types: opened
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
jobs:
  build:
    name: Build
    runs-on: macOS-10.15
    steps:
      - uses: rtCamp/action-slack-notify@v2.0.2
        name: Slack Notifiaction
        env:
          SLACK_TITLE: タイトル
          SLACK_COLOR: good
          SLACK_MESSAGE: メッセージ送信テスト
